export const options = {
  words: [
    "anise",
    "apple",
    "aspic",
    "bacon",
    "bagel",
    "basil",
    "beans",
    "berry",
    "bland",
    "bread",
    "broil",
    "broth",
    "candy",
    "cater",
    "chard",
    "chili",
    "chips",
    "cream",
    "crepe",
    "crisp",
    "crust",
    "curds",
    "curry",
    "dairy",
    "dates",
    "diner",
    "dough",
    "dried",
    "drink",
    "feast",
    "flour",
    "fried",
    "fruit",
    "grain",
    "grape",
    "gravy",
    "guava",
    "herbs",
    "honey",
    "icing",
    "jelly",
    "juice",
    "kebab",
    "knife",
    "ladle",
    "lemon",
    "liver",
    "lunch",
    "maize",
    "mango",
    "melon",
    "mints",
    "mochi",
    "munch",
    "olive",
    "onion",
    "order",
    "pasta",
    "patty",
    "peach",
    "pecan",
    "pilaf",
    "pizza",
    "plate",
    "prune",
    "punch",
    "roast",
    "salad",
    "salsa",
    "sauce",
    "seeds",
    "slice",
    "snack",
    "spicy",
    "spoon",
    "spork",
    "spuds",
    "squid",
    "steak",
    "stove",
    "straw",
    "sugar",
    "sushi",
    "sweet",
    "syrup",
    "thyme",
    "toast",
    "torte",
    "tuber",
    "wafer",
    "water",
    "wheat",
    "camel",
    "horse",
    "llama",
    "egypt",
    "greek",
    "roman",
    "feast",
    "drink",
    "spice",
    "serfs",
    "halal",
    "haram",
    "meats",
    "china",
    "islam",
    "trade",
    "crops",
    "sugar",
    "taytu",
    "maize",
    "seeds",
    "price",
    "cider",
    "irish",
    "diner",
    "japan",
    "paris",
  ],
  history: {
    "anise": "Anise, (Pimpinella anisum), annual herb of the parsley family (Apiaceae), cultivated chiefly for its fruits, called aniseed, the flavour of which resembles that of licorice. Native to Egypt and the eastern Mediterranean region, anise is cultivated in southern Europe, southern Russia, the Middle East, North Africa, Pakistan, China, Chile, Mexico, and the United States. Star anise, an unrelated plant, has a similar flavour profile.",
    "apple": "This is a fruit that is very challenging to cultivate due to quality not being the same as the parent. Grafting is used to farm apples. It was domesticated ~4000-10000 years ago. Originally spread by trade through people along the silk road. It Became an important crop across the world because of its use for cider and it is also an edible fruit. The apple also represents a key crop in the history of food as it spread along the silk road and became popular amongst many different civilizations.",
    "aspic": "Aspic, savoury clear jelly prepared from a liquid stock made by simmering the bones of beef, veal, chicken, or fish. Aspic is used to coat and glaze foods such as cold meats and fish, eggs, poached or roasted poultry, and vegetables. Supposedly, it origins can be traced back to the 10th century Middle East.",
    "bacon": "Bacon, a side of a pig that, after removal of the spare ribs, is cured, either dry or in pickle, and smoked. Bacon was for centuries the staple meat of the western European peasantry. Varieties distinguished by cut of meat or curing process became standardized in association with particular countries or regions, such as the Irish or various Italian styles. The relatively long storage life of bacon made it the only meat to gain importance as an international trade commodity in the late 19th century.",
    "bagel": "Bagel, doughnut-shaped yeast-leavened roll that is characterized by a crisp, shiny crust and a dense interior. Long regarded as a Jewish specialty item, the bagel is commonly eaten as a breakfast food or snack, often with toppings such as cream cheese and lox (smoked salmon). The origin of the bagel is not known, but it seems to have its roots in central Europe. Accounts from the royal court in Poland dating to the 14th century mention obwarzanek, a ring-shaped, boiled, bagel-like bread. A widely repeated legend traces the origin of the bagel itself to Vienna in 1683, when John III Sobieski, king of Poland, successfully defended the city from a Turkish invasion. A local baker, wishing to commemorate the victory of this accomplished horseman, fashioned his bread in the shape of a stirrup (the present-day German word for which is Bügel). In the late 19th century, European Jewish immigrants introduced the bagel to the United States, where it gained a popular association with New York City. The American bagel industry expanded rapidly in the late 20th century; bagel bakeries and frozen-food distributors created numerous variations on the traditional form and texture.",
    "basil": "Basil, (Ocimum basilicum), also called sweet basil, annual herb of the mint family (Lamiaceae), grown for its aromatic leaves. Basil is likely native to India and is widely grown as a kitchen herb. The leaves are used fresh or dried to flavour meats, fish, salads, and sauces; basil tea is a stimulant.",
    "beans": "Bean, (Phaseolus vulgaris), any of a variety of legumes (family Fabaceae) widely cultivated for their edible seeds and seedpods. The common bean is second to the soybean in economic and societal importance as a leguminous food crop. As with other beans, it is rich in protein and provides moderate amounts of iron, thiamin, and riboflavin. Of Central and South American origin, the common bean figures prominently in Latin American and Creole cuisines, though varieties are commonly used fresh or dried in foods around the world.",
    "berry": "Berry, in botany, a simple fleshy fruit that usually has many seeds, such as the banana, grape, and tomato. As a simple fruit, a berry is derived from a single ovary of an individual flower. Any small fleshy fruit is popularly called a berry, especially if it is edible. Raspberries, blackberries, and strawberries, for example, are not true berries but are aggregate fruits—fruits that consist of a number of smaller fruits. Cranberries and blueberries, however, are true botanical berries.",
    "bland": "Refers to the lack of spice or spicyness. This typically also means little to no seasoning is used and there is little to no additional flavor associated with a food item.",
    "bread": "Bread, baked food product made of flour or meal that is moistened, kneaded, and sometimes fermented. A major food since prehistoric times, it has been made in various forms using a variety of ingredients and methods throughout the world. The first bread was made in Neolithic times, nearly 12,000 years ago, probably of coarsely crushed grain mixed with water, with the resulting dough probably laid on heated stones and baked by covering with hot ashes. The Egyptians apparently discovered that allowing wheat doughs to ferment, thus forming gases, produced a light, expanded loaf, and they also developed baking ovens.",
    "broil": "Broiling, cooking by exposing food to direct radiant heat, either on a grill over live coals or below a gas burner or electric coil. Broiling differs from roasting and baking in that the food is turned during the process so as to cook one side at a time. Temperatures are higher for broiling than for roasting. Fish, fowl, and most red meats are suitable for broiling. Steaks, popularly broiled over coals, can also be broiled in skillets or in the oven set on a seasoned wooden plank.",
    "broth": "The basis of many soups is stock, or broth, a rich liquid obtained by boiling fish, meat, poultry, game, or vegetables. Clear broths can be garnished with separately cooked vegetables, pasta or rice, quenelles or dumplings, poached eggs, or other ingredients. Chinese egg-drop and Italian stracciatella are enriched with beaten eggs stirred in the hot broth. Meaty broths were also served in the earliest version of the modern restaurant in Paris during the 18th century. Broths were thought to have the same benefits as eating meat but easier to consume. They were seen as a restorative form of food.",
    "candy": "Candy, also called confectionery, sweet food product, the main constituent of which generally is sugar. The application of the terms candy and confectionery varies among English-speaking countries. In the United States candy refers to both chocolate products and sugar-based confections; elsewhere “chocolate confectionery” refers to chocolates, “sugar confectionery” to the various sugar-based products, and “flour confectionery” to products such as cakes and pastries.",
    "cater": "Catering has a rich history, dating back to the 4th millennium BC in China. Officially, the Ancient Greeks made catering a trade by offering services at their inns and hostels which lasted into the Roman Empire. Throughout the centuries Catering was primarily for feasts and banquets for Kings and Noblemen. In America, catering dates back all the way to our country’s beginning and has continued to evolve as our nation progresses. Take a look at this brief timeline, noting some of the Catering Industries major milestones in the United States of America.",
    "chard": "Chard, (Beta vulgaris), also called Swiss chard, one of the four cultivated forms of the plant Beta vulgaris of the amaranth family (Amaranthaceae), grown for its edible leaves and leafstalks. Fresh chard is highly perishable and difficult to ship to distant markets. The young leaves can be eaten raw in salads, while larger leaves and stalks are commonly sautéed or served in soups. ",
    "chili": "Chili is a hearty stew that is also used as a topping condiment on other dishes and has varied recipes and ingredients, with or without meat, ultimately derived from the Mexican-style chili con carne. Records were found by Everrette DeGolyer (1886-1956), a Dallas millionaire and a lover of chili, indicating that the first chili mix was concocted around 1850 by Texan adventurers and cowboys as a staple for hard times when traveling to and in the California gold fields and around Texas.  Needing hot grub, the trail cooks came up with a sort of stew.  They pounded dried beef, fat, pepper, salt, and the chile peppers together into stackable rectangles which could be easily rehydrated with boiling water.  This amounted to “brick chili” or “chili bricks” that could be boiled in pots along the trail.",
    "chips": "The earliest known recipe for chips dates to 1817, when an English doctor named William Kitchiner published The Cook’s Oracle, a cookbook that included a recipe for “potatoes fried in slices or shavings.” For a long time, chips remained a restaurant-only delicacy. But in 1895 an Ohio entrepreneur named William Tappenden found a way to keep them stocked on grocery shelves, using his kitchen and, later, a barn turned factory in his backyard to make the chips and deliver them in barrels to local markets via horse-drawn wagon. Countless other merchants followed suit.",
    "cream": "Cream, yellowish component of milk, rich in fat globules, that rises to the surface naturally if milk is allowed to stand; in the dairy industry, cream is separated mechanically. In the United States, commercially produced cream is graded for use according to the percentage of fat content.",
    "crepe": "Crepe, also spelled crêpe, French pancake made of a thin batter containing flour, eggs, melted butter, salt, milk, water, and, if the crepes are to be served with a sweet sauce or garnish, sugar. Crepes can be filled with a variety of sweet or savoury mixtures. For crepes suzette the crepes are folded in four and soaked in a syrup flavoured with orange liqueur, and frequently are flamed at table. The word crêpe is derived from crispa, Latin for “curly.”",
    "crisp": "Rather than use the word \"chips\" like we do in America, Brits refer to small thin salty snacks such as potato chips as \"crisps.\"",
    "crust": "Typically refers to pie or pizza. Crust is the tough outer part of a bread food item.",
    "curds": "A soft, white substance formed when milk sours, used as the basis for cheese.",
    "curry": "Curry, in Western usage, is a dish composed with a sauce or gravy seasoned with a mixture of ground spices that is thought to have originated in India and has since spread to many regions of the world. The foundation of many Indian curries is a mixture of onion, ginger, and garlic. That base is flavoured with several spices.",
    "dairy": "Dairy, milk and any of the foods made from milk, including butter, cheese, ice cream, yogurt, and condensed and dried milk.",
    "dates": "Date palm, (Phoenix dactylifera), tree of the palm family (Arecaceae) cultivated for its sweet edible fruits. The date palm has been prized from remotest antiquity and may have originated in what is now Iraq. The fruit has been the staple food and chief source of wealth in the irrigable deserts of North Africa and the Middle East. Spanish missionaries carried the tree to the New World in the 18th and early 19th centuries.",
    "diner": "A person who dines (as in a restaurant) or who is dining (eating in a restaurant).",
    "dough": "Dough, mixture of flour and liquid with other ingredients, such as leavening agents, shortening, sugar, salt, eggs, and various flavourings, used to make baked products. A similar mixture, in more liquefied form, is known as batter. Doughs are used to make breads and pastries. Sweet doughs, used for such products as coffee cakes and Danish pastries, are richer than bread doughs.",
    "dried": "In ancient times the sun and wind would have naturally dried foods. Evidence shows that Middle East and oriental cultures actively dried foods as early as 12,000 B.C. in the hot sun. Later cultures left more evidence and each would have methods and materials to reflect their food supplies—fish, wild game, domestic animals, etc. Vegetables and fruits were also dried from the earliest times. The Romans were particularly fond of any dried fruit they could make. In the Middle Ages purposely built “still houses” were created to dry fruits, vegetables and herbs in areas that did not have enough strong sunlight for drying. A fire was used to create the heat needed to dry foods and in some cases smoking them as well.",
    "drink": "Any fermented liquor, such as wine, beer, or distilled spirits, that contains ethyl alcohol, or ethanol, as an intoxicating agent. Alcoholic beverages are fermented from the sugars in fruits, berries, grains, and such other ingredients as plant saps, tubers, honey, and milk and may be distilled to reduce the original watery liquid to a liquid of much greater alcoholic strength.",
    "feast": "Feasts are a day or period of time set aside to commemorate, ritually celebrate or reenact, or anticipate events or seasons—agricultural, religious, or sociocultural—that give meaning and cohesiveness to an individual and to the religious, political, or socioeconomic community. They typically consist of a large amount of food that is consumed by those taking part in the feast.",
    "flour": "Flour, finely ground cereal grains or other starchy portions of plants, used in various food products and as a basic ingredient of baked goods. Flour made from wheat grains is the most satisfactory type for baked products that require spongy structure. In modern usage, the word flour alone usually refers to wheat flour, the major type in Western countries.",
    "fried": "The cooking of food in hot fats or oils, usually done with a shallow oil bath in a pan over a fire or as so-called deep fat frying, in which the food is completely immersed in a deeper vessel of hot oil. Because the food is heated through a greasy medium, some authorities consider frying to be technically a dry-heat cooking process. The technique of frying is ancient, ubiquitous, and highly versatile; it has been used since antiquity and in most cultures to prepare meats and fish, vegetables, and breads.",
    "fruit": "Fruit, the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Popularly, however, the term is restricted to the ripened ovaries that are sweet and either succulent or pulpy.",
    "grain": "Grain, also called cereal, any grass (family Poaceae) yielding starchy seeds suitable for food. Breads, especially those made with refined flours, are usually enriched in order to compensate for any nutritional deficiencies in the grain used. The grains most commonly cultivated are wheat, rice, rye, oats, barley, corn (maize), and sorghum.",
    "grape": "Grape, (genus Vitis), genus of about 60 to 80 species of vining plants in the family Vitaceae, native to the north temperate zone, including varieties that may be eaten as table fruit, dried to produce raisins, or crushed to make grape juice or wine. The grape is usually a woody vine, climbing by means of tendrils (modified branches) and when untrained often reaching a length of 17 metres (56 feet) or more. In arid regions it may form an almost erect shrub.",
    "gravy": "The term \"gravy\" first appears in Middle English as gravé and is presumed to derive from French, since the word may be found in numerous medieval French cookbooks. The original medieval meaning was precise: the gravé consisted of the natural cooking juices that flowed from roasting meat.",
    "guava": "Guava, (Psidium guajava), small tropical tree or shrub of the family Myrtaceae, cultivated for its edible fruits. Guava trees are native to tropical America and are grown in tropical and subtropical areas worldwide. Guava fruits are processed into jams, jellies, and preserves and are common pastry fillings.",
    "herbs": "The term \"herb\" describe plants or parts of plants used for medicine, cooking, and pleasure all over the world. These plants number in the thousands and come from almost every plant family known. Herbs are the green, leafy parts of plants. They are most efficacious and flavorsome when used fresh, and they are mostly grown in temperate to hot regions.",
    "honey": "Honey, sweet, viscous liquid food, dark golden in colour, produced in the honey sacs of various bees from the nectar of flowers. Flavour and colour are determined by the flowers from which the nectar is gathered. Some of the most commercially desirable honeys are produced from clover by the domestic honeybee.",
    "icing": "Powdered icing sugar, or confectioners’ sugar, results when white granulated sugar is finely ground, sieved, and mixed with small quantities (3 percent) of starch or calcium phosphate to keep it dry.",
    "jelly": "Jelly, a semitransparent confection consisting of the strained juice of various fruits or vegetables, singly or in combination, sweetened, boiled, slowly simmered, and congealed, often with the aid of pectin, gelatin, or a similar substance. The juices of most fruits and berries and many vegetables are suitable for processing into jelly.",
    "juice": "The liquid obtained from or present in fruit or vegetables.",
    "kebab": "Dish of small pieces of lamb threaded on a skewer and cooked over an open fire. The name of the dish is derived from the Turkish şiş, meaning a spit or skewer, and kebab, mutton or lamb. Variants of this dish are found throughout the Balkans, the Middle East, and the Caucasus.",
    "knife": "Tool or implement for cutting, the blade being either fixed to the handle or fastened with a hinge so as to clasp into it.",
    "ladle": "A soup ladle is a specialized spoon which is designed for serving soups, gravies, punches, and other liquids. Ladles can also be used for stirring and in food preparation.",
    "lemon": "lemon, (Citrus), small tree or spreading bush of the rue family (Rutaceae) and its edible fruit. Lemon juice is a characteristic ingredient in many pastries and desserts. The lemon was introduced into Spain and North Africa sometime between the years 1000 and 1200 CE. It was further distributed through Europe by the Crusaders, who found it growing in Palestine. In 1494 the fruit was being cultivated in the Azores and shipped largely to England.",
    "liver": "The Babylonians considered the liver to be the seat and mirror of the soul and, as a consequence, this organ became the focus of divination ceremonies, in which the livers of sacrificial animals were carefully inspected by priests for signs of damage prior to being offered as gifts to the gods. It was the Greeks who first abandoned superstition in favour of an approach to the understanding of the body based on anatomy and physiology, and it is in the writings of Aristotle where the first attempts to describe animals' livers based on dissection are to be found.",
    "lunch": "Lunch, the most informal and unassuming of meals, defies easy definition. A relatively late entry into the cycle of dining, it is replete with socioeconomic forms and meanings. Though the notion of the lunch or luncheon is most often attributed to nineteenth-century Britain, the terms had long been in use in England, albeit in slightly different form. The term has been in use since the Middle Ages as a word for a small snack, often eaten in the fields during the workday and sometimes called nunchin. Dr. Johnson's 1755 Dictionary defines \"luncheon\" as \"as much food as one's hand can hold.\" For many centuries, lunch or luncheon was precisely this: a hunk of food, a few hurried bites of sustenance, a snack.",
    "maize": "Maize, or corn, is a cereal plant of the grass family (Poaceae) and its edible grain. The domesticated crop originated in the Americas and is one of the most widely distributed of the world’s food crops. Maize is used as livestock feed, as human food, as biofuel, and as raw material in industry. Maize was first domesticated by native peoples in southern Mexico about 10,000 years ago. Modern corn/maize is believed to have been derived from the Balsas teosinte (Zea mays parviglumis), a wild grass. ",
    "mango": "Mango, (Mangifera indica), member of the cashew family (Anacardiaceae) and one of the most important and widely cultivated fruits of the tropical world. The mango tree is considered indigenous to southern Asia, especially Myanmar and Assam state of India, and numerous cultivars have been developed. ",
    "melon": "Melon, (Cucumis melo), trailing vine in the gourd family (Cucurbitaceae), grown for its often musky-scented edible fruit. The melon plant is native to central Asia, and its many cultivated varieties are widely grown in warm regions around the world. Most commercially important melons are sweet and eaten fresh, though some varieties can be made into preserves or pickled.",
    "mints": "For natural solutions to the problem of maintaining sweet breath, a small piece of nutmeg or angelica root can be chewed, or a piece of the herb called mace can be placed in the mouth for several minutes. Obviously, the most common herbal breath mints are the mints. A leaf or two from any of the commonly grown mint plants, including peppermint, can be eaten to freshen the breath and aid digestion. Many references about herbs provide recipes for making toothpaste and mouthwash from pepper-mint and other herbs and natural ingredients that avoid the detergents and sugar found in commercial products.",
    "mochi": "The rice cake called mochi was a sweet confection eaten by the nobility during the Nara Period from 710-794 a.d. when the Chinese greatly influenced Japanese culture.",
    "munch": "eat (something) with a continuous and often audible action of the jaws.",
    "olive": "Olive, (Olea europaea), subtropical broad-leaved evergreen tree (family Oleaceae) and its edible fruit. The olive fruit and its oil are key elements in the cuisine of the Mediterranean and are popular outside the region. The edible olive was grown on the island of Crete about 3500 BCE. Semitic peoples apparently cultivated it as early as 3000 BCE. Olive oil was prized for anointing the body in Greece during the time of Homer, and it was an important crop of the Romans about 600 BCE. Later, olive growing spread to all the countries bordering the Mediterranean, and the tree is also planted as an ornamental in suitable climates.",
    "onion": "Onion, (Allium cepa), herbaceous biennial plant in the amaryllis family (Amaryllidaceae), grown for its edible bulb. The onion is likely native to southwestern Asia but is now grown throughout the world, chiefly in the temperate zones. Onions are low in nutrients but are valued for their flavour and are used widely in cooking. They add flavour to such dishes as stews, roasts, soups, and salads and are also served as a cooked vegetable. Onions are among the world’s oldest cultivated plants. They were probably known in India, China, and the Middle East before recorded history. Ancient Egyptians regarded the spherical bulb as a symbol of the universe, and its name is probably derived from the Latin unus, meaning “one.” The Romans introduced the onion to Britain and, in the New World, Native Americans added a highly pungent wild onion to their stews. Curative powers have been attributed to onions throughout the centuries; they have been used in folk medicine.",
    "order": "request (something) to be made, supplied, or served.",
    "pasta": "Pasta, any of several starchy food preparations (pasta alimentaria) frequently associated with Italian cuisine and made from semolina, the granular product obtained from the endosperm of a type of wheat called durum, and containing a large proportion of gluten (elastic protein). It is formed into ribbons, cords, tubes, and various special shapes, all originally developed for specific characteristics, such as ability to retain heat or hold sauces.",
    "patty": "The hamburger or \"burger,\" minimally defined as a cooked ground beef patty between two pieces of bread, was born in America sometime around 1890. Loosely based on the ground-beef steak popular in the German town of Hamburg, the hamburger gained national repute at the 1904 St. Louis World's Fair.",
    "peach": "Peach, (Prunus persica), fruit tree of the rose family (Rosaceae), grown throughout the warmer temperate regions of both the Northern and Southern hemispheres. Peaches are widely eaten fresh and are also baked in pies and cobblers; canned peaches are a staple commodity in many regions.",
    "pecan": "Pecan, (Carya illinoinensis), nut and tree of the walnut family (Juglandaceae) native to temperate North America. Rich and distinctive in flavour and texture, the pecan has one of the highest fat contents of any vegetable product and a caloric value close to that of butter. The pecan may be eaten raw, sweetened or salted. It is widely used in pastries, such as coffee cakes, and often in conjunction with chocolate. In the southeastern United States the pecan pie, consisting of pecans baked in a clear custard, and the pecan praline candy are traditional sweets.",
    "pilaf": "Pilaf is a Persian and Turkish word denoting a rice dish boiled with meat and vegetables, seasoned with spices. But pilaf also means a way of cooking rice—knowing exactly the water-absorption capacity of the rice. In Turkish cuisine, pilaf is usually a side dish. In Persian cuisine, pilaf (pilow) is a main dish with other ingredients added to it. Pilaf is also made with bulgur in Turkey.",
    "pizza": "Pizza, dish of Italian origin consisting of a flattened disk of bread dough topped with some combination of olive oil, oregano, tomato, olives, mozzarella or other cheese, and many other ingredients, baked quickly—usually, in a commercial setting, using a wood-fired oven heated to a very high temperature—and served hot.",
    "plate": "Plate, a flat dish, typically circular and made of china, from which food is eaten or served. Tableware.",
    "prune": "Dried plum.",
    "punch": "A drink made with fruit juices, soda, spices, and sometimes liquor, typically served in small cups from a large bowl.",
    "roast": "Roasting, cooking, primarily of meats but also of corn ears, potatoes, or other vegetables thus prepared, by exposure to dry radiant heat either over an open fire, within a reflecting-surface oven, or in some cases within surrounding hot embers, sand, or stones. The procedure is comparable to the baking of other foods.",
    "salad": "Salad, any of a wide variety of dishes that fall into the following principal categories: green salads; vegetable salads; salads of pasta, legumes, or grains; mixed salads incorporating meat, poultry, or seafood; and fruit salads. Most salads are traditionally served cold. The earliest salads were wild greens and herbs seasoned with salt.",
    "salsa": "Salsa is the Spanish word for sauce, and in Mexico it refers to sauces that are used as an ingredient for a variety of dishes and as a condiment. Most salsas are especially spicy, due to the prominence of hot chili peppers in their ingredients. Salsas have been know for a thousand years in Mexico, yet salsa as we know it today is a fairly well-balanced blend of both Old World and New World ingredients. The tomatoes, tomatillos, and chilies found in salsa are native to this hemisphere, while all the other ingredients, such as onions, garlic, and other spices, are Old World in origin.",
    "sauce": "Sauce, liquid or semiliquid mixture that is added to a food as it cooks or that is served with it. Sauces provide flavour, moisture, and a contrast in texture and colour. They may also serve as a medium in which food is contained, for example, the velouté sauce of creamed chicken. Seasoning liquids (soy sauce, hot pepper sauce, fish sauce, Worcestershire sauce) are used both as ingredients in cooking and at the table as condiments.",
    "seeds": "Essentially, a seed consists of a miniature undeveloped plant (the embryo), which, alone or in the company of stored food for its early development after germination, is surrounded by a protective coat (the testa). Frequently small in size and making negligible demands upon their environment, seeds are eminently suited to perform a wide variety of functions.",
    "slice": "A thin, broad piece of food, such as bread, meat, or cake, cut from a larger portion",
    "snack": "Throughout human history, the frequency and content of meals has varied. From ancient times, light foods or leftovers were consumed between meals. These tended to be natural, sweet foods that required little or no preparation, such as grapes, figs, or apples. In nineteenth-century America, interest in snack foods shifted from natural foods to prepared commercial foods, with a high salt and sugar content. It is these processed foods that are considered snack foods in the early twenty-first century.",
    "spicy": "Flavored with or fragrant with spice.",
    "spoon": "Spoon, an implement consisting of a small shallow bowl-shaped receptacle supported by a handle, used for eating, serving, and cooking foods. Spoons, together with forks, are known as flatware.",
    "spork": "A spork is an eating utensil designed with features of both a spoon and a fork. The overall shape is similar to a spoon complete with a handle and a small bowl-like structure at the end. At the very end of the spork are short tines that are useful for picking up solid food. Also called a runcible spoon, sporks are often provided by take-out restaurants as disposable utensils. They are generally composed of plastic and made through a thermoforming process.",
    "spuds": "The English coined the word \"spud\" for potato, a slang expression that originally referred to a potato-digging spade.",
    "squid": "Squid, any of more than 300 species of 10-armed cephalopods classified within the order Teuthoidea (or Teuthida) and found in both coastal and oceanic waters. Squids are numerous in the sea and serve as food for many animals, including the sperm whale, bony fishes, and human beings.",
    "steak": "High-quality beef taken from the hindquarters of the animal, typically cut into thick slices that are cooked by broiling or frying",
    "stove": "Stove, device used for heating or cooking. The first of historical record was built in 1490 in Alsace, entirely of brick and tile, including the flue. The later Scandinavian stove had a tall, hollow iron flue containing iron baffles arranged to lengthen the travel of the escaping gases in order to extract maximum heat. The Russian stove had as many as six thick-walled masonry flues; it is still widely used in northern countries. The first manufactured cast-iron stove was produced at Lynn, Mass., in 1642. This stove had no grates and was little more than a cast-iron box. About 1740 Benjamin Franklin invented the “Pennsylvania fireplace,” which incorporated the basic principles of the heating stove. The Franklin stove burned wood on a grate and had sliding doors that could be used to control the draft (flow of air) through it. Because the stove was relatively small, it could be installed in a large fireplace or used free-standing in the middle of a room by connecting it to a flue. The Franklin stove warmed farmhouses, city dwellings, and frontier cabins throughout North America. Its design influenced the potbellied stove, which was a familiar feature in some homes well into the 20th century.",
    "straw": "Straw, the stalks of grasses, particularly of such cereal grasses as wheat, oats, rye, barley, and buckwheat. When used collectively, the term straw denotes such stalks in the aggregate after the drying and threshing of grain. Human beings from ancient times have used straw as litter and fodder for cattle, as a covering for floors, for coarse bedding, and even as clothing.",
    "sugar": "Sugar is a broad term applied to a large number of carbohydrates present in many plants and characterized by a more or less sweet taste. The primary sugar, glucose, is a product of photosynthesis and occurs in all green plants. In the sap of some plants, the sugar mixtures are condensed into syrup. Sugar, which had long been considered a luxury available only to the elites of medieval and renaissance Europe, was transformed into a household staple by the colonization of the New World. The combination of conquered tropical and subtropical lands, African slave labor, and capital advanced by northern European merchants transformed the European diet. Furthermore, sugar's importance to overseas trade is reflected in contemporary observations that proclaimed the sugar industry to be at the heart of national wealth",
    "sushi": "Sushi, a staple rice dish of Japanese cuisine, consisting of cooked rice flavoured with vinegar and a variety of vegetable, egg, or raw seafood garnishes and served cold. Restaurants specializing in sushi abound in Japan, where subtleties of preparation find a discriminating clientele. ",
    "sweet": "Having the pleasant taste characteristic of sugar or honey; not salty, sour, or bitter",
    "syrup": "Maple syrup, sweet-water sap of certain North American maple trees, chiefly the sugar maple, Acer saccharum, but also the black maple, Acer nigrum. It was utilized by the Indians of the Great Lakes and St. Lawrence River regions prior to the arrival of European settlers and is still produced solely in North America.",
    "thyme": "Thyme, (Thymus vulgaris), pungent herb of the mint family (Lamiaceae) known for the aroma and flavour of its dried leaves and flowering tops. Thyme is native to Eurasia and is cultivated throughout the world. It is used to flavour a wide range of foods, including poultry, stuffings, fish, eggs, meats, sauces, soups, vegetables, cheeses, and pastas.",
    "toast": "Sliced bread browned on both sides by exposure to heat; the practice of drinking a toast in honor of a person or thing goes back to the late 17th century, and originated in naming a lady whose health the company was requested to drink, the idea being that the lady's name flavoured the drink like the pieces of spiced toast that were formerly placed in drinks such as wine.",
    "torte": "The torte is a very rich cake found throughout Europe, often of numerous thin layers and containing nuts, fruit, creme, and chocolate in combination.",
    "tuber": "A tuber is a swollen, underground storage organ that develops on the roots of certain species of plants. Some types of tubers are highly nutritious, mostly because of their energy content in the form of starch. The white potato is the most important and best-known of the agricultural tubers. The potato is a native of the Andean plateau of South America. In this species, tubers develop at the end of roots that emerge from underground stems, known as stolons.",
    "wafer": "The wafer traces its origin to ancient Egypt, but the descriptive terms applied to it are generally of medieval origin. The wafers of ancient Egypt were prepared from only the finest wheat flour (actually the flour of emmer, a species of primitive wheat).",
    "water": "Tasteless and odourless liquid at room temperature, it has the important ability to dissolve many other substances. Indeed, the versatility of water as a solvent is essential to living organisms. Life is believed to have originated in the aqueous solutions of the world’s oceans, and living organisms depend on aqueous solutions, such as blood and digestive juices, for biological processes.",
    "wheat": "Wheat, any of several species of cereal grasses of the genus Triticum (family Poaceae) and their edible grains. Wheat is one of the oldest and most important of the cereal crops. Most wheat used for food requires processing. The grain is cleaned and then conditioned by the addition of water so that the kernel breaks up properly. In milling, the grain is cracked and then passed through a series of rollers. About 72 percent of the milled grain is recovered as white flour. Flour made from the whole kernel is called graham flour.",
    "camel": "Camel, (genus Camelus), any of three species of large ruminating hoofed mammals of arid Africa and Asia known for their ability to go for long periods without drinking. Camels have long been valued as pack or saddle animals, and they are also exploited for milk, meat, wool, and hides.",
    "horse": "Horse, (Equus caballus), a hoofed herbivorous mammal of the family Equidae. It comprises a single species, Equus caballus, whose numerous varieties are called breeds. Before the advent of mechanized vehicles, the horse was widely used as a draft animal, and riding on horseback was one of the chief means of transportation. In prehistoric times the wild horse was probably first hunted for food. Research suggests that domestication had taken place by approximately 6,000 years ago.",
    "llama": "Llama, (Lama glama), domesticated livestock species, descendant of the guanaco (Lama guanicoe), and one of the South American members of the camel family, Camelidae (order Artiodactyla). The llama is primarily a pack animal, but it is also used as a source of food, wool, hides, tallow for candles, and dried dung for fuel. Llama herds are found primarily in Bolivia, Peru, Colombia, Ecuador, Chile, and Argentina, and they have been exported to other countries.",
    "egypt": "Civilization in northeastern Africa that dates from the 4th millennium BCE. Its many achievements, preserved in its art and monuments, hold a fascination that continues to grow as archaeological finds expose its secrets. Had significant cultural, technological, religious and political impacts on the world.",
    "greek": "Ancient Greek civilization, the period following Mycenaean civilization, which ended about 1200 BCE, to the death of Alexander the Great, in 323 BCE. It was a period of political, philosophical, artistic, and scientific achievements that formed a legacy with unparalleled influence on Western civilization. The appreciation of food in ancient Greece—by those who had the time and money—marks the beginning of what is known today as gastronomy. Greek literary texts (especially comic plays) of around 350 b.c.e. present detailed discussions of which foods were consumed, how much they cost, and how they would be prepared. From the same period one can trace the beginnings of the idea that each city would have its own local food specialities and its own distinctive wine.",
    "roman": "The greatest and most influential multicultural empire in world history to date. It is of particular importance for Christianity, because Christ was born under the reign of Augustus, and the early Church developed in the milieu of Greco-Roman civilization within the Roman Empire and was subject to its government. In Late Antiquity, the Roman Empire collapsed in Western Europe, and the year 476, when the last emperor of Rome was dethroned, has become a date of convenience for the fall of the Roman Empire. In the eastern Mediterranean, however, the Roman Empire continued, developing seamlessly into the Byzantine Empire which lasted until Constantinople fell to the Ottoman Turks in 1453.",
    "spice": "The terms \"spice\" describe plants or parts of plants used for medicine, cooking, and pleasure all over the world. Spices are usually used in small amounts, are best used dry (the drying process often enhances the flavor), and most grow in subtropical or tropical climates. Desire for spices drove trade all across the world and significantly guided the course of food history.",
    "serfs": "A tenant farmer was bound to a hereditary plot of land and to the will of his landlord. The vast majority of serfs in medieval Europe obtained their subsistence by cultivating a plot of land that was owned by a lord. This was the essential feature differentiating serfs from slaves, who were bought and sold without reference to a plot of land. The serf provided his own food and clothing from his own productive efforts. A substantial proportion of the grain the serf grew on his holding had to be given to his lord.",
    "halal": "Permissible food practices under Islam",
    "haram": "Forbidden food practices under Islam",
    "meats": "The flesh or other edible parts of animals (usually domesticated cattle, swine, and sheep) used for food, including not only the muscles and fat but also the tendons and ligaments.",
    "china": "Ancient China was very influential on the history of food through the spread of various food items along the silk road, the creation of the earliest known restaurants, and the cultural impact that China had on all of East and Southeast Asia.",
    "islam": "Islam, major world religion promulgated by the Prophet Muhammad in Arabia in the 7th century CE.",
    "trade": "Various networks of trade drove the history of food to a much more global scope. This was done through various trade systems like the Silk Road, Columbian Exchange and the demand for Cod.",
    "crops": "Crops, in agriculture, a plant or plant product that can be grown and harvested extensively for profit or subsistence. y use, crops fall into six categories: food crops, for human consumption (e.g., wheat, potatoes); feed crops, for livestock consumption (e.g., oats, alfalfa); fibre crops, for cordage and textiles (e.g., cotton, hemp); oil crops, for consumption or industrial uses (e.g., cottonseed, corn); ornamental crops, for landscape gardening (e.g., dogwood, azalea); and industrial and secondary crops, for various personal and industrial uses (e.g., rubber, tobacco).",
    "taytu": "Taytu was the wife of Menelik II who held a five dya feast to christen a new church in Addis Ababa (Ethiopia) in 1887. This feast was held to make social and political connections to bridge gaps between various cultures in Ethiopia to form a nation.",
    "price": "Price is an important attribute when dicussing the history of food because it addresses a shift in how food is acquired. Rather than farming, hunting or finding one's own food, people began to buy and sell food. Prices led to new forms of weatlh and specialization but they also led to new disasters such as the price famine.",
    "cider": "Cider, the expressed juice of a fruit—typically apples—used as a beverage.",
    "irish": "Group of people under British rule that ultimately faced and suffered serious loss of life due to a price famine associated with a disease that hurt their primary source of nutrition, potatoes.",
    "japan": "Very influential country in East Asia that popularized sushi and many other culturally specific dishes.",
    "paris": "Birthplace of the modern restaurant that resulted from \"bouillon restaurateur\". These establishments were primarily available to elites and offered service and choice for all its customers.",
  }
};
